export const internationalOrigins = [
  {
    addressLine1: 'Weilong',
    addressLine2: 'High-tech Zone',
    addressLine3: 'Logistics Park',
    city: 'Zhaoqing',
    state: 'Guangdong',
    postalCode: '528999',
    countryCode: 'CN',
  },
  {
    addressLine1: 'Northern Light Center',
    addressLine2: '#8/9 ST AIRPORT',
    addressLine3: 'LOGISTICS ZONE',
    city: 'Beijing',
    postalCode: '101300',
    state: 'BJ',
    countryCode: 'CN',
  },
];

export const domesticOrigins = [
  {
    city: 'Nashville',
    addressLine1: '1616 west end ave',
    addressLine2: 'unit 2504',
    postalCode: '37203',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Greeneville',
    addressLine1: '1010 Hartman Rd',
    postalCode: '37743',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Murfreesboro',
    addressLine1: '1538 North Side Dr',
    postalCode: '37130',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Atlanta',
    addressLine1: '782 Peachtree St NE',
    addressLine2: 'unit 1121',
    postalCode: '30308',
    state: 'GA',
    countryCode: 'US',
  },
  {
    city: 'Charleston',
    addressLine1: '700 Quay Cr',
    addressLine2: 'unit 711',
    postalCode: '29412',
    state: 'SC',
    countryCode: 'US',
  },
  {
    city: 'Spartanburg',
    addressLine1: '105 Gable Court',
    postalCode: '29307',
    state: 'SC',
    countryCode: 'US',
  },
  {
    city: 'Greenville',
    addressLine1: '27 Lisa Dr',
    postalCode: '29615',
    state: 'SC',
    countryCode: 'US',
  },
  {
    city: 'North Olmsted',
    addressLine1: '24399 Rosita Ln',
    postalCode: '44070',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Springfield',
    addressLine1: '815 Bellevue Avenue',
    postalCode: '45503',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Springboro',
    addressLine1: '8667 shelly woods Ct',
    postalCode: '45066',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Henrico',
    addressLine1: '2830 Ackley Ave',
    addressLine2: 'suite 108',
    postalCode: '23228',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Chesterfield',
    addressLine1: '7700 Qualla Road',
    postalCode: '23832',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Norfolk',
    addressLine1: '330 West Brambleton Avenue',
    postalCode: '23510',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Eagle',
    addressLine1: '134 Greenhorn Ave',
    addressLine2: 'x4626',
    postalCode: '81631',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Durango',
    addressLine1: '6 Ferringway Cir',
    addressLine2: 'unit 39',
    postalCode: '81301',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Crested Butte',
    addressLine1: '148 Elcho Ave',
    addressLine2: 'Unit 7 pbox 4234',
    postalCode: '81224',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Pensacola Beach',
    addressLine1: '1390 Fort Pickens Road',
    addressLine2: 'unit 252',
    postalCode: '32561',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Cocoa',
    addressLine1: '115 N Indian River Dr',
    addressLine2: 'unit 209',
    postalCode: '32922',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Miami',
    addressLine1: '20515 E Country Club Dr',
    addressLine2: 'unit 1746',
    postalCode: '33180',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Hawthorne',
    addressLine1: '13809 Hawthorne Way Apt D',
    addressLine2: 'upstairs',
    postalCode: '90250',
    state: 'CA',
    countryCode: 'US',
  },
  {
    city: 'Laguna',
    addressLine1: '620 Griffith Way',
    addressLine2: 'upper level',
    postalCode: '92651',
    state: 'CA',
    countryCode: 'US',
  },
];

export const domesticDestinations= [
  {
    city: 'Seattle',
    addressLine1: '816 3rd Ave',
    postalCode: '98104',
    state: 'WA',
    countryCode: 'US',
  },
  {
    city: 'Birmingham',
    addressLine1: '901 Bankhead Hwy W',
    postalCode: '35204',
    state: 'AL',
    countryCode: 'US',
  }, {
    city: 'Hauppauge',
    addressLine1: '694 Motor Pkwy',
    addressLine2: 'Suite 15',
    postalCode: '11788',
    state: 'NY',
    countryCode: 'US',
  }, {
    city: 'Dallas',
    addressLine1: '1301 Chalk Hill Rd',
    addressLine2: 'Suite 77B',
    postalCode: '75211',
    state: 'TX',
    countryCode: 'US',
  },
  {
    city: 'Nashville',
    addressLine1: '1616 west end ave',
    addressLine2: 'unit 2504',
    postalCode: '37203',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Greeneville',
    addressLine1: '1010 Hartman Rd',
    postalCode: '37743',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Murfreesboro',
    addressLine1: '1538 North Side Dr',
    postalCode: '37130',
    state: 'TN',
    countryCode: 'US',
  },
  {
    city: 'Chamblee',
    addressLine1: '5070 peachtree blvd',
    addressLine2: 'unit 1348',
    postalCode: '30341',
    state: 'GA',
    countryCode: 'US',
  },
  {
    city: 'Atlanta',
    addressLine1: '782 Peachtree St NE',
    addressLine2: 'unit 1121',
    postalCode: '30308',
    state: 'GA',
    countryCode: 'US',
  },
  {
    city: 'Charleston',
    addressLine1: '700 Quay Cr',
    addressLine2: 'unit 711',
    postalCode: '29412',
    state: 'SC',
    countryCode: 'US',
  },
  {
    city: 'Spartanburg',
    addressLine1: '105 Gable Court',
    postalCode: '29307',
    state: 'SC',
    countryCode: 'US',
  },
  {
    city: 'North',
    addressLine1: 'Olmsted   24399 Rosita Ln',
    postalCode: '44070',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Springfield',
    addressLine1: '815 Bellevue Avenue',
    postalCode: '45503',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Springboro',
    addressLine1: '8667 shelly woods Ct',
    postalCode: '45066',
    state: 'OH',
    countryCode: 'US',
  },
  {
    city: 'Henrico',
    addressLine1: '2830 Ackley Ave',
    addressLine2: 'suite 108',
    postalCode: '23228',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Chesterfield',
    addressLine1: '7700 Qualla Road',
    postalCode: '23832',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Norfolk',
    addressLine1: '330 West Brambleton Avenue',
    postalCode: '23510',
    state: 'VA',
    countryCode: 'US',
  },
  {
    city: 'Eagle',
    addressLine1: '134 Greenhorn Ave',
    addressLine2: 'x4626',
    postalCode: '81631',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Durango',
    addressLine1: '6 Ferringway Cir',
    addressLine2: 'unit 39',
    postalCode: '81301',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Crested Butte',
    addressLine1: '148 Elcho Ave',
    addressLine2: 'Unit 7 pbox 4234',
    postalCode: '81224',
    state: 'CO',
    countryCode: 'US',
  },
  {
    city: 'Long Island City',
    addressLine1: '57th ave',
    addressLine2: 'unit 5219',
    postalCode: '11101',
    state: 'NY',
    countryCode: 'US',
  },
  {
    city: 'Queens',
    addressLine1: '3734 33rd st',
    addressLine2: 'unit 3B',
    postalCode: '11101',
    state: 'NY',
    countryCode: 'US',
  },
  {
    city: 'Brooklyn',
    addressLine1: '1158 45 Street',
    addressLine2: 'top floor',
    postalCode: '11219',
    state: 'NY',
    countryCode: 'US',
  },
  {
    city: 'Pensacola',
    addressLine1: 'Beach 1390 Fort Pickens Road',
    addressLine2: 'unit 252',
    postalCode: '32561',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Cocoa',
    addressLine1: '115 N Indian River Dr',
    addressLine2: 'unit 209',
    postalCode: '32922',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Miami',
    addressLine1: '20515 E Country Club Dr',
    addressLine2: 'unit 1746',
    postalCode: '33180',
    state: 'FL',
    countryCode: 'US',
  },
  {
    city: 'Hawthorne',
    addressLine1: '13809 Hawthorne Way Apt D',
    addressLine2: 'upstairs',
    postalCode: '90250',
    state: 'CA',
    countryCode: 'US',
  },
  {
    city: 'Laguna',
    addressLine1: '620 Griffith Way',
    addressLine2: 'upper level',
    postalCode: '92651',
    state: 'CA',
    countryCode: 'US',
  },
];
